// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: proto/gps.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_gps_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type GetAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetAddress) Reset() {
	*x = GetAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddress) ProtoMessage() {}

func (x *GetAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddress.ProtoReflect.Descriptor instead.
func (*GetAddress) Descriptor() ([]byte, []int) {
	return file_proto_gps_proto_rawDescGZIP(), []int{1}
}

func (x *GetAddress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1 float64 `protobuf:"fixed64,1,opt,name=p1,proto3" json:"p1,omitempty"`
	P2 float64 `protobuf:"fixed64,2,opt,name=p2,proto3" json:"p2,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_gps_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetP1() float64 {
	if x != nil {
		return x.P1
	}
	return 0
}

func (x *Point) GetP2() float64 {
	if x != nil {
		return x.P2
	}
	return 0
}

type MyPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr     string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Location *Point `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *MyPoint) Reset() {
	*x = MyPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyPoint) ProtoMessage() {}

func (x *MyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyPoint.ProtoReflect.Descriptor instead.
func (*MyPoint) Descriptor() ([]byte, []int) {
	return file_proto_gps_proto_rawDescGZIP(), []int{3}
}

func (x *MyPoint) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MyPoint) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_proto_gps_proto protoreflect.FileDescriptor

var file_proto_gps_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x22, 0x26, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x70,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x70,
	0x32, 0x22, 0x41, 0x0a, 0x07, 0x4d, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x12, 0x22, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x32, 0x2d, 0x0a, 0x05, 0x4d, 0x79, 0x47, 0x70, 0x73, 0x12, 0x24, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x08, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x08, 0x2e, 0x4d, 0x79, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x67, 0x70, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gps_proto_rawDescOnce sync.Once
	file_proto_gps_proto_rawDescData = file_proto_gps_proto_rawDesc
)

func file_proto_gps_proto_rawDescGZIP() []byte {
	file_proto_gps_proto_rawDescOnce.Do(func() {
		file_proto_gps_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gps_proto_rawDescData)
	})
	return file_proto_gps_proto_rawDescData
}

var file_proto_gps_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gps_proto_goTypes = []any{
	(*Address)(nil),    // 0: Address
	(*GetAddress)(nil), // 1: GetAddress
	(*Point)(nil),      // 2: Point
	(*MyPoint)(nil),    // 3: MyPoint
}
var file_proto_gps_proto_depIdxs = []int32{
	2, // 0: MyPoint.location:type_name -> Point
	0, // 1: MyGps.GetMyAddress:input_type -> Address
	3, // 2: MyGps.GetMyAddress:output_type -> MyPoint
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gps_proto_init() }
func file_proto_gps_proto_init() {
	if File_proto_gps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gps_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gps_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gps_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gps_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MyPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gps_proto_goTypes,
		DependencyIndexes: file_proto_gps_proto_depIdxs,
		MessageInfos:      file_proto_gps_proto_msgTypes,
	}.Build()
	File_proto_gps_proto = out.File
	file_proto_gps_proto_rawDesc = nil
	file_proto_gps_proto_goTypes = nil
	file_proto_gps_proto_depIdxs = nil
}
