// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/gps.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyGps_GetMyAddress_FullMethodName = "/MyGps/GetMyAddress"
)

// MyGpsClient is the client API for MyGps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyGpsClient interface {
	GetMyAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*MyPoint, error)
}

type myGpsClient struct {
	cc grpc.ClientConnInterface
}

func NewMyGpsClient(cc grpc.ClientConnInterface) MyGpsClient {
	return &myGpsClient{cc}
}

func (c *myGpsClient) GetMyAddress(ctx context.Context, in *Address, opts ...grpc.CallOption) (*MyPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyPoint)
	err := c.cc.Invoke(ctx, MyGps_GetMyAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyGpsServer is the server API for MyGps service.
// All implementations must embed UnimplementedMyGpsServer
// for forward compatibility.
type MyGpsServer interface {
	GetMyAddress(context.Context, *Address) (*MyPoint, error)
	mustEmbedUnimplementedMyGpsServer()
}

// UnimplementedMyGpsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyGpsServer struct{}

func (UnimplementedMyGpsServer) GetMyAddress(context.Context, *Address) (*MyPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyAddress not implemented")
}
func (UnimplementedMyGpsServer) mustEmbedUnimplementedMyGpsServer() {}
func (UnimplementedMyGpsServer) testEmbeddedByValue()               {}

// UnsafeMyGpsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyGpsServer will
// result in compilation errors.
type UnsafeMyGpsServer interface {
	mustEmbedUnimplementedMyGpsServer()
}

func RegisterMyGpsServer(s grpc.ServiceRegistrar, srv MyGpsServer) {
	// If the following call pancis, it indicates UnimplementedMyGpsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyGps_ServiceDesc, srv)
}

func _MyGps_GetMyAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyGpsServer).GetMyAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyGps_GetMyAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyGpsServer).GetMyAddress(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

// MyGps_ServiceDesc is the grpc.ServiceDesc for MyGps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyGps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MyGps",
	HandlerType: (*MyGpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyAddress",
			Handler:    _MyGps_GetMyAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gps.proto",
}
